// Precaches everything so Reef works offline and opens instantly. The cache
// name carries the version, so a new version means a new cache and the old one
// is deleted on activate. Every path is relative, so this works from
// https://<user>.github.io/reef/ as well as from a domain root.
const CACHE = 'reef-v0.15.0-yll0qv';

// PRECACHE-START — regenerated by tools/set-version.mjs; do not edit by hand.
const PRECACHE = [
  './',
  './index.html',
  './style.css',
  './manifest.webmanifest',
  './js/bag.js',
  './js/behaviours.js',
  './js/boids.js',
  './js/camera.js',
  './js/config.js',
  './js/creatures/base.js',
  './js/creatures/travellers.js',
  './js/creatures/zone1.js',
  './js/creatures/zone2.js',
  './js/creatures/zone3.js',
  './js/creatures/zone4.js',
  './js/creatures/zone5.js',
  './js/creatures/zone6.js',
  './js/creatures/zone7.js',
  './js/debug/diagnostics.js',
  './js/debug/menu.js',
  './js/debug/registry.js',
  './js/debug/scene.js',
  './js/effects.js',
  './js/fps.js',
  './js/glossary/panel.js',
  './js/glossary/seen.js',
  './js/landmarks/common.js',
  './js/landmarks/dropoff.js',
  './js/landmarks/midnight.js',
  './js/landmarks/open.js',
  './js/landmarks/reef.js',
  './js/landmarks/shallows.js',
  './js/landmarks/twilight.js',
  './js/landmarks/vents.js',
  './js/main.js',
  './js/memory.js',
  './js/palette.js',
  './js/particles.js',
  './js/perf.js',
  './js/registry.js',
  './js/save.js',
  './js/settings/panel.js',
  './js/settings/settings.js',
  './js/spawner.js',
  './js/sprites/shapes.js',
  './js/sprites.js',
  './js/title.js',
  './js/ui/buttons.js',
  './js/ui/panel.js',
  './js/ui/rows.js',
  './js/updates.js',
  './js/version.js',
  './js/vignettes/base.js',
  './js/vignettes/director.js',
  './js/vignettes/fx.js',
  './js/vignettes/zone1.js',
  './js/vignettes/zone2.js',
  './js/vignettes/zone3.js',
  './js/vignettes/zone4.js',
  './js/vignettes/zone5.js',
  './js/vignettes/zone6.js',
  './js/vignettes/zone7.js',
  './js/wakelock.js',
  './js/water.js',
  './js/world.js',
  './icons/icon-180.png',
  './icons/icon-192.png',
  './icons/icon-512-maskable.png',
  './icons/icon-512.png',
];
// PRECACHE-END

self.addEventListener('install', (e) => {
  e.waitUntil(
    caches.open(CACHE)
      // One failed entry must not fail the whole install.
      .then((c) => Promise.all(PRECACHE.map((u) => c.add(u).catch(() => {}))))
      .then(() => self.skipWaiting()),
  );
});

self.addEventListener('activate', (e) => {
  e.waitUntil(
    caches.keys()
      .then((keys) => Promise.all(keys.filter((k) => k !== CACHE).map((k) => caches.delete(k))))
      .then(() => self.clients.claim()),
  );
});

self.addEventListener('fetch', (e) => {
  const req = e.request;
  if (req.method !== 'GET') return;
  const url = new URL(req.url);
  if (url.origin !== self.location.origin) return;
  e.respondWith(
    caches.match(req).then((hit) => hit || fetch(req).then((res) => {
      // Keep the cache warm for anything fetched that was not precached.
      if (res && res.ok && res.type === 'basic') {
        const copy = res.clone();
        caches.open(CACHE).then((c) => c.put(req, copy)).catch(() => {});
      }
      return res;
    }).catch(() => (req.mode === 'navigate' ? caches.match('./') : undefined))),
  );
});
